# How to run on GPU

Step 1) Go to https://github.com/settings/tokens and get a token that can read your private repos

Step 2) Clone this colab notebook and change the execution environment to GPU.

Step 3) Install python 3.8

Step 4) Clone and install your code.

Step 5) Run the command-line code for training.

## Step 3: Install python 3.8
Run the cell below without editing it.

In [2]:
!sudo apt-get update -y
!sudo apt-get install python3.8
!curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
!python3.8 get-pip.py

Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,113 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:7 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,482 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-upda

## Step 4: Clone and install your code
First we need to set some environment variables. Get your github API token and MLE repo username and put them into the below variables.

In [3]:
from google.colab import userdata
import os
os.environ['TOKEN'] = userdata.get('github_api_token')

In [4]:
# %env TOKEN=token
%env USER=mitkrieg

env: USER=mitkrieg


Run the below code. Editing should not be necessary.

In [5]:
TOKEN = %env TOKEN
USER = %env USER
%env DIR=mod3-$USER
DIR = %env DIR

# !echo https://$TOKEN@github.com/Cornell-Tech-ML/$DIR

!git clone -b master --single-branch https://$TOKEN@github.com/Cornell-Tech-ML/$DIR
!cd $DIR; pip3 install -r requirements.txt; pip3 install -r requirements.extra.txt; pip3 install .

env: DIR=mod3-mitkrieg
Cloning into 'mod3-mitkrieg'...
remote: Enumerating objects: 183, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (40/40), done.
Receiving objects: 100% (183/183), 84.37 KiB | 14.06 MiB/s, done.
remote: Total 183 (delta 80), reused 77 (delta 74), pack-reused 69 (from 1)
Resolving deltas: 100% (99/99), done.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 5.3 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of pytest-env to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 389.6/389.6 kB 33.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 72.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.5/199.5 kB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 32.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.0/99.0 kB 10.7 MB/s eta 0:00:00


In [ ]:
import minitorch
t = minitorch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
t


[
	[1.00 2.00 3.00]
	[4.00 5.00 6.00]
	[7.00 8.00 9.00]]

In [ ]:
minitorch.fast_ops.FastOps.matrix_multiply(t,t)


[
	[30.00 36.00 42.00]
	[66.00 81.00 96.00]
	[102.00 126.00 150.00]]

In [ ]:
minitorch.cuda_ops.CudaOps.matrix_multiply(t,t)

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))



[
	[30.00 36.00 42.00]
	[66.00 81.00 96.00]
	[102.00 126.00 150.00]]

In [ ]:
!ls

get-pip.py  mod3-mitkrieg  sample_data


In [5]:
!pytest mod3-mitkrieg/tests/ -m task3_2

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /content/mod3-mitkrieg
configfile: pyproject.toml
plugins: env-1.1.4, hypothesis-6.54.0, typeguard-4.4.1, anyio-3.7.1
collected 117 items / 115 deselected / 2 selected                                                  

mod3-mitkrieg/tests/test_tensor_general.py ..                                                [100%]

================================ 2 passed, 115 deselected in 21.27s ================================


In [6]:
!pytest mod3-mitkrieg/tests/ -m task3_3

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /content/mod3-mitkrieg
configfile: pyproject.toml
plugins: env-1.1.4, hypothesis-6.54.0, typeguard-4.4.1, anyio-3.7.1
collected 117 items / 60 deselected / 57 selected                                                  

mod3-mitkrieg/tests/test_tensor_general.py ................................................. [ 85%]
........                                                                                     [100%]

========================================= warnings summary =========================================
tests/test_tensor_general.py: 16 warnings
  /usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
    warn(NumbaPerformanceWarning(msg))

tests/test_tensor_general.py: 4274 warnings
  /usr/

In [ ]:
a = minitorch.tensor(
    [
	[
		[0.00, 0.00],
		[0.00, 0.00]],
	[
		[0.00, 0.00],
		[0.00, 0.00]]
 ]
)
b = minitorch.tensor([
	[
		[0.00, 0.00],
		[0.00, 0.00]],
	[
		[0.00, 0.00],
		[0.00, 1.00]]]
)
z = minitorch.fast_ops.FastOps.matrix_multiply(a, b)
z



[
	[
		[0.00 0.00]
		[0.00 0.00]]
	[
		[0.00 0.00]
		[0.00 0.00]]]

In [ ]:
k = minitorch.cuda_ops.CudaOps.matrix_multiply(a, b)
k



[
	[
		[0.00 0.00]
		[0.00 0.00]]
	[
		[0.00 0.00]
		[0.00 0.00]]]

In [7]:
!pytest mod3-mitkrieg/tests/ -m task3_4

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /content/mod3-mitkrieg
configfile: pyproject.toml
plugins: env-1.1.4, hypothesis-6.54.0, typeguard-4.4.1, anyio-3.7.1
collected 117 items / 110 deselected / 7 selected                                                  

mod3-mitkrieg/tests/test_tensor_general.py .......                                           [100%]

========================================= warnings summary =========================================
tests/test_tensor_general.py::test_mul_practice1
tests/test_tensor_general.py::test_mul_practice3
tests/test_tensor_general.py::test_mul_practice3
tests/test_tensor_general.py::test_bmm[cuda]
tests/test_tensor_general.py::test_bmm[cuda]
tests/test_tensor_general.py::test_bmm[cuda]
  /usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely resul

In [8]:
!cd $DIR; pwd; python3 timing.py

/content/mod3-mitkrieg
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 2 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
Running size 64
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 8 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
{'fast': np.float64(0.0036759376525878906), 'gpu': np.float64(0.006918589274088542)}
Running size 128
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 32 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
{'fast': np.flo

If you update your code, you can re-pull the repo by running this cell.

In [16]:
!cd $DIR; pwd; git pull origin master; pip3 install --force-reinstall --no-cache-dir .

/content/mod3-mitkrieg
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5 (delta 3), reused 5 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 964 bytes | 964.00 KiB/s, done.
From https://github.com/Cornell-Tech-ML/mod3-mitkrieg
 * branch            master     -> FETCH_HEAD
   f5fbb84..f441a0d  master     -> origin/master
Updating f5fbb84..f441a0d
Fast-forward
 project/run_fast_tensor.py |  2 +-
 timing.py                  | 58 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 59 insertions(+), 1 deletion(-)
 create mode 100644 timing.py
Processing /content/mod3-mitkrieg
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for minitorch: filename=minitorch-0.5-py2.py3-none-any.whl size=31751 sha256=67ba38a92618aab8f3d36af170c33ac6f8b3b410704ef638c89de8e05

## Step 5: Run the training command

### Simple

In [18]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND cpu --HIDDEN 100 --DATASET split --RATE 0.05

Epoch:     0 || Loss:  8.32548 || Correct    25 || Time per epoch:  18.39554
Epoch:    10 || Loss:  6.47043 || Correct    40 || Time per epoch:  0.09881
Epoch:    20 || Loss:  3.99787 || Correct    39 || Time per epoch:  0.09808
Epoch:    30 || Loss:  2.95462 || Correct    39 || Time per epoch:  0.09782
Epoch:    40 || Loss:  5.75990 || Correct    46 || Time per epoch:  0.09822
Epoch:    50 || Loss:  2.24706 || Correct    48 || Time per epoch:  0.14127
Epoch:    60 || Loss:  1.54707 || Correct    44 || Time per epoch:  0.15890
Epoch:    70 || Loss:  2.59027 || Correct    49 || Time per epoch:  0.09943
Epoch:    80 || Loss:  3.07012 || Correct    49 || Time per epoch:  0.10017
Epoch:    90 || Loss:  3.73035 || Correct    45 || Time per epoch:  0.09817
Epoch:   100 || Loss:  2.40822 || Correct    50 || Time per epoch:  0.09741
Epoch:   110 || Loss:  2.12735 || Correct    49 || Time per epoch:  0.09832
Epoch:   120 || Loss:  1.31102 || Correct    50 || Time per epoch:  0.09887
Epoch:   13

In [17]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND gpu --HIDDEN 100 --DATASET split --RATE 0.05

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 7 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 4 will likely result in GPU under-utilization due

In [19]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND cpu --HIDDEN 500 --DATASET split --RATE 0.05

Epoch:     0 || Loss:  26.63657 || Correct    39 || Time per epoch:  18.94309
Epoch:    10 || Loss:  4.42665 || Correct    44 || Time per epoch:  0.83532
Epoch:    20 || Loss:  1.08549 || Correct    49 || Time per epoch:  0.82688
Epoch:    30 || Loss:  2.25921 || Correct    48 || Time per epoch:  0.74359
Epoch:    40 || Loss:  2.47335 || Correct    44 || Time per epoch:  0.84621
Epoch:    50 || Loss:  0.73759 || Correct    49 || Time per epoch:  0.79610
Epoch:    60 || Loss:  0.32806 || Correct    49 || Time per epoch:  0.77416
Epoch:    70 || Loss:  1.79367 || Correct    49 || Time per epoch:  0.84081
Epoch:    80 || Loss:  0.80014 || Correct    49 || Time per epoch:  0.78349
Epoch:    90 || Loss:  0.09830 || Correct    47 || Time per epoch:  0.79658
Epoch:   100 || Loss:  1.13797 || Correct    49 || Time per epoch:  0.84541
Epoch:   110 || Loss:  0.03126 || Correct    49 || Time per epoch:  0.76781
Epoch:   120 || Loss:  0.13515 || Correct    49 || Time per epoch:  0.80149
Epoch:   1

In [20]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND gpu --HIDDEN 500 --DATASET split --RATE 0.05

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 32 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 16 will likely result in GPU under-utilization d

### Split

In [21]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND cpu --HIDDEN 100 --DATASET split --RATE 0.05

Epoch:     0 || Loss:  4.07173 || Correct    32 || Time per epoch:  18.16308
Epoch:    10 || Loss:  4.52326 || Correct    39 || Time per epoch:  0.09813
Epoch:    20 || Loss:  5.17273 || Correct    46 || Time per epoch:  0.09768
Epoch:    30 || Loss:  3.45568 || Correct    45 || Time per epoch:  0.09738
Epoch:    40 || Loss:  1.34912 || Correct    47 || Time per epoch:  0.09745
Epoch:    50 || Loss:  2.84589 || Correct    50 || Time per epoch:  0.17305
Epoch:    60 || Loss:  1.40761 || Correct    47 || Time per epoch:  0.13012
Epoch:    70 || Loss:  1.40857 || Correct    47 || Time per epoch:  0.09842
Epoch:    80 || Loss:  1.10346 || Correct    46 || Time per epoch:  0.09778
Epoch:    90 || Loss:  2.20721 || Correct    46 || Time per epoch:  0.09666
Epoch:   100 || Loss:  1.50759 || Correct    49 || Time per epoch:  0.09809
Epoch:   110 || Loss:  1.46235 || Correct    47 || Time per epoch:  0.10250
Epoch:   120 || Loss:  1.18130 || Correct    48 || Time per epoch:  0.09846
Epoch:   13

In [7]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND gpu --HIDDEN 100 --DATASET split --RATE 0.05

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 7 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 4 will likely result in GPU under-utilization due

### XOR

In [22]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND cpu --HIDDEN 100 --DATASET xor --RATE 0.05

Epoch:     0 || Loss:  6.80791 || Correct    28 || Time per epoch:  18.22354
Epoch:    10 || Loss:  4.28319 || Correct    37 || Time per epoch:  0.09793
Epoch:    20 || Loss:  2.93311 || Correct    44 || Time per epoch:  0.09738
Epoch:    30 || Loss:  3.23911 || Correct    44 || Time per epoch:  0.09757
Epoch:    40 || Loss:  2.63329 || Correct    45 || Time per epoch:  0.10524
Epoch:    50 || Loss:  2.51675 || Correct    45 || Time per epoch:  0.17248
Epoch:    60 || Loss:  2.72185 || Correct    45 || Time per epoch:  0.12250
Epoch:    70 || Loss:  1.28917 || Correct    46 || Time per epoch:  0.09658
Epoch:    80 || Loss:  1.48718 || Correct    46 || Time per epoch:  0.09691
Epoch:    90 || Loss:  0.74941 || Correct    46 || Time per epoch:  0.09767
Epoch:   100 || Loss:  2.23547 || Correct    46 || Time per epoch:  0.09663
Epoch:   110 || Loss:  1.35189 || Correct    45 || Time per epoch:  0.09711
Epoch:   120 || Loss:  1.30326 || Correct    46 || Time per epoch:  0.09703
Epoch:   13

In [23]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND gpu --HIDDEN 100 --DATASET xor --RATE 0.05

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 7 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 4 will likely result in GPU under-utilization due

In [15]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND cpu --HIDDEN 500 --DATASET xor --RATE 0.05

Epoch:     0 || Loss:  76.92976 || Correct    32 || Time per epoch:  18.34954
Epoch:    10 || Loss:  1.35926 || Correct    47 || Time per epoch:  0.73230
Epoch:    20 || Loss:  3.21588 || Correct    46 || Time per epoch:  0.84166
Epoch:    30 || Loss:  3.05700 || Correct    49 || Time per epoch:  0.86942
Epoch:    40 || Loss:  3.17658 || Correct    47 || Time per epoch:  0.75742
Epoch:    50 || Loss:  1.94909 || Correct    49 || Time per epoch:  0.82322
Epoch:    60 || Loss:  0.93115 || Correct    49 || Time per epoch:  0.83951
Epoch:    70 || Loss:  0.34140 || Correct    49 || Time per epoch:  0.73307
Epoch:    80 || Loss:  0.66406 || Correct    48 || Time per epoch:  0.83509
Epoch:    90 || Loss:  2.30551 || Correct    50 || Time per epoch:  0.84786
Epoch:   100 || Loss:  3.61139 || Correct    47 || Time per epoch:  0.72473
Epoch:   110 || Loss:  0.83126 || Correct    49 || Time per epoch:  0.83262
Epoch:   120 || Loss:  1.97192 || Correct    50 || Time per epoch:  0.83627
Epoch:   1

In [14]:
!cd $DIR; PYTHONPATH=/content/$DIR python3 project/run_fast_tensor.py --BACKEND gpu --HIDDEN 500 --DATASET xor --RATE 0.05

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 32 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:888: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:536: NumbaPerformanceWarning: Grid size 16 will likely result in GPU under-utilization d